#!/usr/bin/ruby
my_name = 'zeb a. shawn'
my_age = 35 #not a lie
my_height = 74 # inches
my_weight = 180 #Ibs
my_eyes = 'Blue'
my_teeth = 'White'
my_hair = 'Brown'

puts "lets talk about %s." % my_name
puts "He's %d inches tall." % my_height
puts "he's %d pounds heavy." % my_weight
puts "actually that's not too heavy."
puts "He's got %s eyes and %s hair." % [my_eyes, my_hair]
puts "his theeth are usually %s depending on the coffee." % my_teeth

# this line is tricky, try to get it exactly right
puts"If i add %d, %d, and %d i get %d." % [
    my_age, my_height, my_weight, my_age + my_height + my_weight]

